
workoutJson = [{
  "activityid": 217,
  "activityname": "WorkOut",
  "created": "2018-06-16",
  "createdby": "Poorna Kola",
  "updated": "2018-06-16",
  "updatedby": "Poorna Kola",
  "WorkoutPrograms": [
    {
      "BodyPart": "FullBody",
      "Difficulty": "Beginner",
      "Frequency": "4",
      "Weeks" : "4",
      "Duration": "40",
      "Routine": "None",
      "ShortDescription": "Sample Beginner Program",
      "Type": "Bulking",
      "WorkoutId": 1,
      "PreviewLink": "https://www.jefit.com/images/exercises/50_50/8.jpg",
      "WorkoutName": "Sample Beginner Program",
      "ProgramRoutines": [
        {
          "RoutineId": "123",
          "Musle": "Chest and tricepts",
          "PreviewLink": "https://www.jefit.com/images/exercises/50_50/32.jpg",
          "Week": "1",
          "Day": "1",
          "Duration": "40",
          "Sequence": "1",
          "DailyRoutines": [
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "1",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "2",
              "ExerciseName": "Barbell Bench Press",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Chest",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/8.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "2",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Barbell Decline Bench Press",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Chest",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/20.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "3",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "4",
              "ExerciseName": "Barbell Incline Bench Press",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Chest",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/32.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "4",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Butterfly",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Chest",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/180.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "5",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "6",
              "ExerciseName": "Cable Cross Over",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Chest",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/56.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "6",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Cable Rope Triceps Pushdown",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Triceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/636.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "7",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "EZ Bar Lying Close Grip Behind the Head Triceps Extension",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Triceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/924.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "8",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "EZ Bar Triceps Extension",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Triceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/884.jpg",
              "Routine": "Beginner"
            }
          ]
        },
        {
          "RoutineId": "124",
          "Musle": "Back and Lats",
          "PreviewLink": "https://www.jefit.com/images/exercises/50_50/360.jpg",
          "Week": "1",
          "Day": "2",
          "Duration": "40",
          "Sequence": "2",
          "DailyRoutines": [
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "1",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Cable Seated Row",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/84.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "2",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "	Cable Straight Arm Push Down",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/732.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "3",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "4",
              "ExerciseName": "Dumbbell One Arm Row",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/360.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "4",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Iso Lateral Wide Pulldown",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5072.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "5",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "6",
              "ExerciseName": "Wide Grip Lat Pulldown",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/344.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "6",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Back Extension Machine",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5036.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "7",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Barbell Deadlift",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/372.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "8",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "T Bar Row",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Back",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/208.jpg",
              "Routine": "Beginner"
            }
          ]
        },
        {
          "RoutineId": "125",
          "Musle": "Legs",
          "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5236.jpg",
          "Week": "1",
          "Day": "3",
          "Duration": "40",
          "Sequence": "3",
          "DailyRoutines": [
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "1",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Smith Machine Squat",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/540.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "2",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Seated Leg Curl with One Leg",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5028.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "3",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "4",
              "ExerciseName": "Seated Leg Curl",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/644.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "4",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Lying Machine Squat",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/516.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "5",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "6",
              "ExerciseName": "Leg Press with Wide Stance",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5236.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "6",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Leg Extensions",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/520.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "7",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Leg Extension with One Leg",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Upper Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5024.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "8",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Standing Calf Raises",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Lower Legs",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/580.jpg",
              "Routine": "Beginner"
            }
          ]
        },
        {
          "RoutineId": "126",
          "Musle": "Biceps",
          "PreviewLink": "https://www.jefit.com/images/exercises/50_50/5236.jpg",
          "Week": "1",
          "Day": "4",
          "Duration": "40",
          "Sequence": "4",
          "DailyRoutines": [
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "1",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Cable Reverse Grip Curls",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Biceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/416.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "2",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "3",
              "ExerciseName": "Cable Standing Curl",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Biceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/2812.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "3",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "4",
              "ExerciseName": "Dumbbell Alternate Bicep Curl",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Biceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/464.jpg",
              "Routine": "Beginner"
            },
            {
              "Reps": "8",
              "RestTime": "60",
              "Sequence": "4",
              "Sets": "3",
              "Duration": "1m",
              "ExerciseId": "5",
              "ExerciseName": "Dumbbell Concentration Curls",
              "Difficulty": "Beginner",
              "Type": "General",
              "Muscle": "Biceps",
              "PreviewLink": "https://www.jefit.com/images/exercises/50_50/428.jpg",
              "Routine": "Beginner"
            }
          ]
        }
      ]
    }
  ]
},
{
  "activityid": 218,
  "activityname": "Meditation",
  "created": "2018-06-16",
  "createdby": "Poorna Kola",
  "updated": "2018-06-16",
  "updatedby": "Poorna Kola",
}]