"""empty message

Revision ID: 1d5494403fad
Revises: d9767e394b24
Create Date: 2018-08-13 23:41:14.243723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5494403fad'
down_revision = 'd9767e394b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Day', sa.Integer(), nullable=True),
    sa.Column('Duration', sa.Integer(), nullable=True),
    sa.Column('Musle', sa.String(length=50), nullable=True),
    sa.Column('PreviewLink', sa.String(length=250), nullable=True),
    sa.Column('RoutineId', sa.Integer(), nullable=True),
    sa.Column('Sequence', sa.Integer(), nullable=True),
    sa.Column('Week', sa.Integer(), nullable=True),
    sa.Column('workoutprogram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workoutprogram_id'], [u'workout_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_routines')
    # ### end Alembic commands ###
