"""empty message

Revision ID: 78c910eeecc2
Revises: b4825f844917
Create Date: 2018-08-19 00:40:05.529184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c910eeecc2'
down_revision = 'b4825f844917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_routines', sa.Column('programroutine_id', sa.Integer()))
    op.create_foreign_key(None, 'daily_routines', 'program_routines', ['programroutine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.drop_column('daily_routines', 'programroutine_id')
    # ### end Alembic commands ###
