"""empty message

Revision ID: c6d57dd3b54e
Revises: 78c910eeecc2
Create Date: 2018-08-24 16:49:42.694657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d57dd3b54e'
down_revision = '78c910eeecc2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('previewLink', sa.String(length=256), nullable=True))
    op.alter_column('daily_routines', 'programroutine_id',
              existing_type=sa.INTEGER(),
              nullable=False)
    op.create_foreign_key(None, 'daily_routines', 'program_routines', ['programroutine_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.alter_column('daily_routines', 'programroutine_id',
              existing_type=sa.INTEGER(),
              nullable=True)
    op.drop_column('activity', 'previewLink')
    ### end Alembic commands ###
