"""empty message

Revision ID: e009fc9e642b
Revises: fc02ac578e44
Create Date: 2018-09-05 23:54:29.021040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e009fc9e642b'
down_revision = 'fc02ac578e44'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('daily_routines', 'programroutine_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.create_foreign_key(None, 'daily_routines', 'program_routines', ['programroutine_id'], ['id'])
    op.add_column('workout_programs', sa.Column('createdDate', sa.DateTime(), nullable=True))
    op.add_column('workout_programs', sa.Column('updatedDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_programs', 'updatedDate')
    op.drop_column('workout_programs', 'createdDate')
    # op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    # op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Muscle'], ['muscle'])
    # op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Type'], ['type'])
    # op.create_foreign_key(None, 'daily_routines', 'Exercises', ['PreviewLink'], ['previewLink'])
    # op.create_foreign_key(None, 'daily_routines', 'Exercises', ['ExerciseName'], ['name'])
    # op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Routine'], ['routine'])
    # op.alter_column('daily_routines', 'programroutine_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###
