"""empty message

Revision ID: fc02ac578e44
Revises: c6d57dd3b54e
Create Date: 2018-08-30 00:05:29.653729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc02ac578e44'
down_revision = 'c6d57dd3b54e'
branch_labels = None
depends_on = None


def upgrade():
    # pass
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercises', sa.Column('detailedMuscle', sa.String(), nullable=True))
    op.add_column('Exercises', sa.Column('equipment', sa.String(), nullable=True))
    op.add_column('Exercises', sa.Column('mechanics', sa.String(), nullable=True))
    op.add_column('Exercises', sa.Column('otherMuscle', sa.String(), nullable=True))
    op.drop_column('Exercises', 'routine')
    op.alter_column('daily_routines', 'programroutine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.create_foreign_key(None, 'daily_routines', 'program_routines', ['programroutine_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    # pass
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_routines', type_='foreignkey')
    op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Muscle'], ['muscle'])
    op.create_foreign_key(None, 'daily_routines', 'Exercises', ['PreviewLink'], ['previewLink'])
    op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Routine'], ['routine'])
    op.create_foreign_key(None, 'daily_routines', 'Exercises', ['Type'], ['type'])
    op.create_foreign_key(None, 'daily_routines', 'Exercises', ['ExerciseName'], ['name'])
    op.alter_column('daily_routines', 'programroutine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Exercises', sa.Column('routine', sa.VARCHAR(), nullable=False))
    op.drop_column('Exercises', 'otherMuscle')
    op.drop_column('Exercises', 'mechanics')
    op.drop_column('Exercises', 'equipment')
    op.drop_column('Exercises', 'detailedMuscle')
    ### end Alembic commands ###
